// ═══════════════════════════════════════════════════════════════
// NyayaGPT — PDF Generation Utility
// ═══════════════════════════════════════════════════════════════

import PDFDocument from 'pdfkit';

/**
 * Generates a styled PDF from a judgment summary.
 * @param {Object} summary The summary JSON data from Gemini
 * @param {NodeJS.WritableStream} stream The output writable stream (e.g. Express Response)
 */
export function generateSummaryPDF(summary, stream) {
  // A4 dimensions: 595.28 x 841.89 points
  const doc = new PDFDocument({ 
    margin: 50, 
    size: 'A4',
    bufferPages: true 
  });

  // Pipe the PDF document to the output stream
  doc.pipe(stream);

  // Document Title Header
  doc.fillColor('#2C3E50')
     .font('Helvetica-Bold')
     .fontSize(22)
     .text(summary.title || 'Judgment Summary', { align: 'center' });

  doc.moveDown(0.5);

  // Metadata Subtitle
  doc.fillColor('#7F8C8D')
     .font('Helvetica-Bold')
     .fontSize(10)
     .text(summary.court ? summary.court.toUpperCase() : 'COURT NOT SPECIFIED', { align: 'center' });

  if (summary.date) {
    doc.fillColor('#95A5A6')
       .font('Helvetica')
       .fontSize(9)
       .text(`Date of Judgment: ${summary.date}`, { align: 'center' });
  }

  doc.moveDown(1.5);

  // Horizontal Accent Divider Line
  doc.strokeColor('#BDC3C7')
     .lineWidth(1)
     .moveTo(50, doc.y)
     .lineTo(545, doc.y)
     .stroke();

  doc.moveDown(1);

  // Section Rendering Helper
  const renderSection = (title, content) => {
    if (!content || (Array.isArray(content) && content.length === 0)) return;

    // Keep heading and first content line on same page if near bottom
    if (doc.y > 720) {
      doc.addPage();
    }

    doc.fillColor('#6C5CE7') // Premium Brand Purple Accent Color
       .font('Helvetica-Bold')
       .fontSize(12)
       .text(title.toUpperCase());
    
    doc.moveDown(0.3);

    doc.fillColor('#2C3E50') // Dark Charcoal Gray Text for high readability
       .font('Helvetica')
       .fontSize(10.5);

    if (Array.isArray(content)) {
      content.forEach(item => {
        doc.text(`•  ${item}`, {
          paragraphGap: 5,
          indent: 12,
          lineGap: 3
        });
      });
    } else {
      doc.text(content, {
        paragraphGap: 8,
        lineGap: 3.5
      });
    }

    doc.moveDown(1.2);
  };

  // Render all judgment summary components
  renderSection('Facts of the Case', summary.facts);
  renderSection('Identified Legal Issues', summary.issues);
  renderSection('Arguments of the Petitioner', summary.petitioner_arguments);
  renderSection('Arguments of the Respondent', summary.respondent_arguments);
  renderSection('Court Reasoning & Statutes Applied', summary.court_reasoning);
  renderSection('Final Verdict / Decision', summary.verdict);
  renderSection('Key Takeaways & Precedent Guidelines', summary.key_takeaways);

  // Add page numbers in footer across all buffered pages
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fillColor('#BDC3C7')
       .font('Helvetica')
       .fontSize(8)
       .text(
         `Page ${i + 1} of ${range.count}  |  Generated by NyayaGPT AI Workspace`,
         50, 
         800, 
         { align: 'center', width: 495 }
       );
  }

  doc.end();
}
